name: Mon Premier Pipeline DevOps

# 1. Quand le robot doit-il travailler ? 
on:
  push:
    branches: [ "main" ] # Dès qu'on envoie du code sur la branche main

jobs:
  build-and-test:
    runs-on: ubuntu-latest # Le robot utilise un serveur Linux gratuit de GitHub

    steps:
      # 2. Le robot récupère ton code
      - name: Recupérer le code
        uses: actions/checkout@v3

      # 3. Le robot installe Python
      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # 4. Le robot installe les dépendances et teste l'API
      - name: Installer les outils et tester
        run: |
          pip install -r requirements.txt
          # Ici on pourrait ajouter des tests automatiques

      # 5. Le robot vérifie que Docker arrive à construire l'image
      - name: Verifier le Build Docker
        run: docker build -t portfolio-test .